language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4

install:
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/behat
  - vendor/bin/behat --profile=mezzio
  - vendor/bin/behat --profile=slim
